# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IstioAxslog < Formula
  desc "istio-axslog is parsed istio-proxy(envoy) access log and output in any format."
  homepage "https://github.com/rnakamine/istio-axslog"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rnakamine/istio-axslog/releases/download/v0.0.4/istio-axslog_0.0.4_darwin_amd64.tar.gz"
      sha256 "e4a819c32567feb09b165f34c12c75b749170e98e111e79960dde698587e7596"

      def install
        bin.install "istio-axslog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rnakamine/istio-axslog/releases/download/v0.0.4/istio-axslog_0.0.4_darwin_arm64.tar.gz"
      sha256 "16b24b4a127e9851776792be291684ce451d938f133325359605f4987d6529e4"

      def install
        bin.install "istio-axslog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rnakamine/istio-axslog/releases/download/v0.0.4/istio-axslog_0.0.4_linux_arm64.tar.gz"
      sha256 "a332637aa21fbfc8cf21b2169c0076b96b67e5610b11e14f8132d7e58b6c7788"

      def install
        bin.install "istio-axslog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rnakamine/istio-axslog/releases/download/v0.0.4/istio-axslog_0.0.4_linux_amd64.tar.gz"
      sha256 "3162ecd329ca623292cb5bd0b239f0c29e6baf0c75e6c35eec22d80b4e3839ce"

      def install
        bin.install "istio-axslog"
      end
    end
  end

  test do
    system "#{bin}/istio-axslog -v"
  end
end
