# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IstioAxslog < Formula
  desc "istio-axslog is parsed istio-proxy(envoy) access log and output in any format."
  homepage "https://github.com/rnakamine/istio-axslog"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rnakamine/istio-axslog/releases/download/v0.0.2/istio-axslog_0.0.2_darwin_arm64.tar.gz"
      sha256 "6f72f80ee40771d6812a621d5c217d99250b24124f3d19cb6e6476fa6d849c79"

      def install
        bin.install "istio-axslog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rnakamine/istio-axslog/releases/download/v0.0.2/istio-axslog_0.0.2_darwin_amd64.tar.gz"
      sha256 "95c6d898e20551dddf76b4d3f90447679bc50958fbdff5fc8f1d6a8c5f76032e"

      def install
        bin.install "istio-axslog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rnakamine/istio-axslog/releases/download/v0.0.2/istio-axslog_0.0.2_linux_arm64.tar.gz"
      sha256 "321b8a630ee9f3b1b6ef0cfc3ee6ccc4284ccadbef7aa36a0a4c30472b7d7f5d"

      def install
        bin.install "istio-axslog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rnakamine/istio-axslog/releases/download/v0.0.2/istio-axslog_0.0.2_linux_amd64.tar.gz"
      sha256 "1db10b5a2231f9d7498d0a51f62342b763b5c73c623d9275723abf1262da200f"

      def install
        bin.install "istio-axslog"
      end
    end
  end

  test do
    system "#{bin}/istio-axslog -v"
  end
end
