# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IstioAxslog < Formula
  desc "istio-axslog is parsed istio-proxy(envoy) access log and output in any format."
  homepage "https://github.com/rnakamine/istio-axslog"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rnakamine/istio-axslog/releases/download/v0.0.3/istio-axslog_0.0.3_darwin_arm64.tar.gz"
      sha256 "5cf38f861d87360005dc02bfac3ea4244a8df451e68156b54ecf265887838487"

      def install
        bin.install "istio-axslog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rnakamine/istio-axslog/releases/download/v0.0.3/istio-axslog_0.0.3_darwin_amd64.tar.gz"
      sha256 "c12f0f9a924359fca344e85708e172ee7118e7c43f823e1853c3c7cbfbee7d96"

      def install
        bin.install "istio-axslog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rnakamine/istio-axslog/releases/download/v0.0.3/istio-axslog_0.0.3_linux_arm64.tar.gz"
      sha256 "a45233a1b6401acf69b464262469ea6cd71ea888c3951a7801d3a4a32c287d31"

      def install
        bin.install "istio-axslog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rnakamine/istio-axslog/releases/download/v0.0.3/istio-axslog_0.0.3_linux_amd64.tar.gz"
      sha256 "d4435a078f033aece1bd61db3841a323b30e4059fbf4904483c00b55be58aeaf"

      def install
        bin.install "istio-axslog"
      end
    end
  end

  test do
    system "#{bin}/istio-axslog -v"
  end
end
